language: c

os:
  - linux

before_install:
  - sudo pip install gcovr
  - sudo apt-get update -qq && sudo apt-get install --assume-yes --quiet gcc-multilib && sudo apt-get install -qq
  - sudo apt-get -q -y install astyle

install:
  - gem install ceedling

script:
  - ceedling test:all
  - ceedling gcov:all utils:gcov
  - astyle --recursive ./src/*.c ./src/*.h > astyle.out
  - git diff --exit-code --diff-filter=d --color
  