language: c

os:
  - linux

before_install:
  - wget -q -O - https://files.viva64.com/etc/pubkey.txt | sudo apt-key add -
  - sudo wget https://files.viva64.com/etc/viva64.list -O /etc/apt/sources.list.d/viva64.list
  - sudo pip install gcovr
  - sudo apt-get update -qq && sudo apt-get install --assume-yes --quiet gcc-multilib && sudo apt-get install -qq
  - sudo apt-get -q -y install astyle
  - sudo apt-get install -qq pvs-studio 

install:
  - gem install ceedling
  - pvs-studio-analyzer credentials $PVS_USERNAME $PVS_KEY

script:
  - ceedling test:all
  - ceedling gcov:all utils:gcov
  - astyle --recursive ./src/*.c ./src/*.h > astyle.out
  - git diff --exit-code --diff-filter=d --color
  - make 
  